djangojokes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # include urls path to the pages app
    path('jokes', include('jokes.urls')),
    path('', include('pages.urls')),
]

jokes/urls.py
from django.urls import path

from .views import (
  JokeListView, JokeDetailView, JokeCreateView, JokeUpdateView
)

app_name = 'jokes'
urlpatterns = [
  # url as jokes/
  path('', JokeListView.as_view(), name='list'),
  
  # path joke/<int:pk>/ indicates that the value entered for this
  # part of the path must be an integer. 
  # The view has access to this value via self.kwargs.get('pk') 
  # and will use it to get the specific joke object to use
  # url as jokes/joke/2
  path('joke/<int:pk>/', JokeDetailView.as_view(), name='detail'),

  # path to update joke urls as example jokes/joke/2/update
  path('joke/<int:pk>/update', JokeUpdateView.as_view(), name='update'),

  # path to create joke with rul as jokes/joke/create
  path('joke/create', JokeCreateView.as_view(), name='create'),
]

pages/urls.py
# urls path for pages app

from django.urls import path
from django.urls.resolvers import URLPattern

from .views import AboutUsView, HomePageView

app_name = 'pages'
urlpatterns = [
  path('', HomePageView.as_view(), name='homepage'),
  path('about-us/', AboutUsView.as_view(), name='about-us'),
]

jokes/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Joke(models.Model):
  question = models.TextField(max_length=200)
  answer = models.TextField(max_length=100, blank=True)
  # auto_now_add=True - field will automatically be assigned 
  # current date and time when the row is created
  created = models.DateTimeField(auto_now_add=True)
  # auto_now=True - value of field will be changed to current
  # date and time when the row is updated
  updated = models.DateTimeField(auto_now=True)

  # alertnative to constructing URLs with get_absolute_url() method
  # define below to called in the templates\jokes\joke_list.html as 
  # href="{{ joke.get_absolute_url }}"> instead of
  # href="{% url 'jokes:detail' joke.pk %}">

  def get_absolute_url(self):
    return reverse('jokes:detail', args=[str(self.pk)])
  
  # __str__() method - return output of the row convert to a string
  def __str__(self):
    return self.question

jokes/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic import CreateView, DetailView, ListView, UpdateView

from .models import Joke

# List view of all jokes 
class JokeListView(ListView):
  model = Joke

# Detail view of a joke inherit from DetailView class
class JokeDetailView(DetailView):
  model = Joke

# Create View to display the joke with data column in html form fields
class JokeCreateView(CreateView):
  model = Joke
  fields = ['question', 'answer']

# Update View to display the joke with data in form fields for update
class JokeUpdateView(UpdateView):
  model = Joke
  fields = ['question', 'answer']

pages/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic import TemplateView

# Home page template
class HomePageView(TemplateView):
  template_name = 'pages/home.html'

# About_Us template
class AboutUsView(TemplateView):
  template_name = 'pages/about_us.html'

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- ADD BOOTSTRAP CSS FROM https://getbootstrap.com/ -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
  integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" 
  crossorigin="anonymous">
<!--
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
  integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
  crossorigin="anonymous">
-->
<!-- ADD FONT AWESOME FROM https://fontawesome.com/ -->
<link href="https://site-assets.fontawesome.com/releases/v6.2.0/css/all.css" 
  rel="stylesheet">
<title>{% block title %}{% endblock %} | Django Jokes</title>
</head>
<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- <div class="container-fluid"> -->
    <!--
      bootstrap classes change from v4.5 to v5.2:
      - change data-toggle to data-bs-toggle on button tag
      - change data-target to data-bs-target on button tag
      - change mr-auto to me-auto on ul tag class navbar-nav
      - add ps-3 to navbar-brand to padding at beginning of brand name
    -->
    <a class="navbar-brand ps-3" href="#">Django Jokes</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent" aria-expanded="false"
      aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pages:homepage' %}">Home 
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'jokes:list' %}">Jokes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Log in</a>
        </li>
        <li class="nav-item dropdown">
          <!--
            bootstrap class changed from v4.5 to v5.2:
            - change data-toggle to data-bs-toggle
            - change div dropdown-menu to ul tag
          -->          
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
             role="button" data-bs-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">
            Me
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">My Account</a>
            <a class="dropdown-item" href="#">My Django Jokes</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Log out</a>
          </ul>
        </li>
      </ul>
      <!--
        bootstrap classes change from v4.5 to v5.2:
        - change form class from form-inline to d-flex
        - add padding end (right) pe-3 for space between search button to the edge 
      -->
      <form class="d-flex my-2 my-lg-0 pe-3">
        <input class="form-control me-sm-2" type="search"
        placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-2" type="submit">
          Search
        </button>
      </form>
    </div>
    <!-- </div> -->
  </nav>
</header>
<main class="m-4 pb-5">
  {% block main %}<h2>Welcome!</h2>{% endblock %}
</main>
<footer class="fixed-bottom bg-light row">
  <div class="col">
    <!--
      bootstrap classes change from v4.5 to v5.2:
      - div class float-right to float-end and mr-2 to me-2
    -->
    <div class="float-end m-1 me-2">Copyright &copy; 2020 Django Jokes.</div>
      <nav>
        <ul class="nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'pages:about-us' %}">About</a></li>
          <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
        </ul>
      </nav>
  </div>
  <!-- </nav> remove extra end nav tag -->
</footer>
<!-- ADD BOOTSTRAP JS FROM https://getbootstrap.com/ -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" 
  integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" 
  crossorigin="anonymous">
</script>
<!--
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
-->
</body>
</html>
</script>
</body>
</html>

templates/jokes/joke_detail.html
{% extends "_base.html" %}

{% block title %}Joke{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 text-center"
    style="max-width: 30rem">
    <div class="card-header">{{ joke.question }}</div>
    <div class="card-body text-primary">
    <h5 class="card-title">{{ joke.answer }}</h5>
    </div>
    <div class="card-footer">
      <small class="text-muted">
        Created on: {{ joke.created }}<br>
        Last updated: {{ joke.updated }}
      </small>
    </div>
  </div>
{% endblock %}

templates/jokes/joke_form.html
{% extends "_base.html" %}

{% comment %}
template to create/update (add/edit) the joke in html form 
- extends _base.html for header, navigation menus and footer 
- include form with a post method
- {% csrf_token %} template tag - security to protect against cross site request forgery
- {{ form }} - output the form fields and their labels
{% endcomment %}

{% block title %}Add/Update Joke{% endblock %}

{% block main %}
  <div class="card border-primary m-auto ms-3 p-3"
    style="max-width: 30rem">
    <form method="post">
      {% csrf_token %}
      <table class="table">
        {{ form.as_table }}
      </table>
      <!-- {{ form }} replace plain form with table -->
      <button class="btn btn-success float-end">Submit</button>
    </form>
  </div>
{% endblock %}

templates/jokes/joke_list.html
{% extends "_base.html" %}

{% block title %}Jokes{% endblock%}
{% block main %}
  <!-- add a link like a button to create/add new joke -->
  <a href="{% url 'jokes:create' %}" class="btn btn-success btn-sm float-end">+ New Joke</a>
  <h2>Jokes</h2>
  <ul class="list-group list-group-flush ms-3">
    {% for joke in joke_list %}
      <li class="list-group-item">
        {% comment %}
        # use get_absolute_url method defined in jokes/models.py to get detail 
        # of link joke instead of joke.pk with the advantage that don't have to
        # change the template if change the way that URLs are constructed 
        {% endcomment %}
        <a href="{{ joke.get_absolute_url }}">{{ joke.question }}</a>
        <!-- <a href="{% url 'jokes:detail' joke.pk %}">{{ joke.question }}</a> -->

        {% comment %}
        # add a update link looks like a button to right of joke
        {% endcomment %}     
        <a href="{% url 'jokes:update' joke.pk %}"
          class="btn btn-info btn-sm float-end me-2">Update</a>
    </li>
    {% endfor%}
  </ul>
{% endblock%}

templates/pages/about_us.html
{% extends "_base.html" %}

{% comment %}
About Us page extends the _base.html file in templates folder
{% endcomment %}

{% block title %}About Us{% endblock %}
{% block main %}
  <h2>About Us</h2>
  <p>We tell funny jokes</p>
{% endblock %}

templates/pages/home.html
{% extends "_base.html" %}

{% comment %}
Home page extends the _base.html file in templates folder
{% endcomment %}

{% block title %}Home{% endblock %}
{% block main %}
  <h2>Welcome To Django Jokes Website</h2>
  <p>Ready to laugh?</p>
{% endblock %}